# Generated by Django 4.2.23 on 2026-03-09 10:28

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_wishlist_unique_together_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='label',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
    ]
