# Generated by Django 4.2.30 on 2026-05-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_terrariumproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrariumproduct',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_of_stock', 'Out of Stock'), ('pre_order', 'Pre Order')], default='in_stock', max_length=50),
        ),
        migrations.AddField(
            model_name='terrariumproduct',
            name='category',
            field=models.CharField(choices=[('succulent', 'Succulent'), ('moss', 'Moss'), ('closed', 'Closed Terrarium'), ('open', 'Open Terrarium'), ('mini', 'Mini Terrarium')], default='succulent', max_length=100),
        ),
        migrations.AddField(
            model_name='terrariumproduct',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='terrariumproduct',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terrariumproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terrariumproduct',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
