# Generated by Django 4.2.30 on 2026-05-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_terrariumproduct_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrariumproduct',
            name='category',
            field=models.CharField(choices=[('Succulent', 'Succulent'), ('Moss', 'Moss'), ('Closed', 'Closed Terrarium'), ('Open', 'Open Terrarium'), ('Mini', 'Mini Terrarium')], default='succulent', max_length=100),
        ),
    ]
