# Generated by Django 4.2.30 on 2026-05-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TerrariumProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('bonsai', 'Bonsai'), ('terrarium', 'Terrarium')], default='bonsai', max_length=20),
        ),
    ]
