# Generated by Django 4.2.30 on 2026-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Show this product in the 'Latest Products' section on the homepage"),
        ),
    ]
